-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  old_price numeric,
  image text not null,
  badge text,
  tagline text,
  use text[],
  style text,
  customizable boolean default false,
  description text,
  stock integer default 0
);

-- Enable RLS
alter table public.products enable row level security;

-- Create policy to allow read access for all
create policy "Allow public read access"
  on public.products
  for select
  to public
  using (true);

-- Create orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  status text default 'pending',
  total numeric not null,
  payment_status text default 'unpaid',
  shipping_address jsonb
);

-- Enable RLS for orders
alter table public.orders enable row level security;

-- Create policy to allow users to see their own orders
create policy "Users can view own orders"
  on public.orders
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Create policy to allow users to insert their own orders
create policy "Users can insert own orders"
  on public.orders
  for insert
  to authenticated
  with check (auth.uid() = user_id);
