-- Allow nullable user_id for guest checkout
alter table public.orders alter column user_id drop not null;

-- Create order items table if not exists
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references public.orders not null,
  product_id bigint references public.products not null,
  quantity integer not null,
  price numeric not null,
  customization jsonb
);

-- Enable RLS
alter table public.order_items enable row level security;

-- Policies for order items
create policy "Public read order items"
  on public.order_items for select
  to public
  using (true);

create policy "Public insert order items"
  on public.order_items for insert
  to public
  with check (true);

-- RPC Function to create order transactionally
create or replace function create_order(
  p_user_id uuid,
  p_items jsonb,
  p_total numeric,
  p_status text,
  p_shipping_address jsonb
)
returns bigint
language plpgsql
as $$
declare
  v_order_id bigint;
  v_item jsonb;
begin
  -- Insert Order
  insert into public.orders (user_id, status, total_amount, shipping_address)
  values (p_user_id, p_status, p_total, p_shipping_address)
  returning id into v_order_id;

  -- Insert Items
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.order_items (order_id, product_id, quantity, price, customization)
    values (
      v_order_id,
      (v_item->>'product_id')::bigint,
      (v_item->>'quantity')::integer,
      (v_item->>'price')::numeric,
      coalesce(v_item->'customization', '{}'::jsonb)
    );
  end loop;

  return v_order_id;
end;
$$;
