const postgres = require('postgres');
require('dotenv').config({ path: '.env.local' });

const sql = postgres(process.env.DATABASE_URL, {
  ssl: { rejectUnauthorized: false },
});

async function migrate() {
  try {
    console.log('Starting migration...');
    
    // 1. Allow nullable user_id for guest checkcounts
    await sql`ALTER TABLE public.orders ALTER COLUMN user_id DROP NOT NULL;`;
    console.log('Updated orders table (user_id is now nullable).');

    // 2. Create order_items table
    await sql`
      CREATE TABLE IF NOT EXISTS public.order_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE,
        product_id bigint REFERENCES public.products(id),
        quantity integer NOT NULL,
        price numeric NOT NULL,
        customization jsonb,
        created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
      );
    `;
    console.log('Created order_items table.');

    console.log('Migration completed successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Migration failed:', err);
    process.exit(1);
  }
}

migrate();
